name: Release package workflow
on:
    release:
        types:
            - released
jobs:
    release:
        name: Release package on Github Packages
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            - uses: zendesk/checkout@v4
            - uses: zendesk/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"
                  cache-dependency-path: "package-lock.json"
                  registry-url: https://npm.pkg.github.com/

            - name: Install dependencies
              run: npm ci

            - name: Build package
              run: npm run build

            - name: Publish to Github Packages
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
